version: "3.9"

services:
  baseline_http:
    build:
      context: ..
      dockerfile: model_optimizations/baseline_service/Dockerfile
    container_name: tx-baseline-http
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /app/model_artifacts/v2_tfidf_linearsvc_model.joblib
      MODEL_VERSION: v1
      CODE_VERSION: dev

  baseline_eval:
    build:
      context: ..
      dockerfile: model_optimizations/Dockerfile.baseline_notebook
    container_name: tx-baseline-eval
    depends_on:
      - baseline_http
    environment:
      BASE_URL: http://baseline_http:8000
      OUTPUT_DIR: /workspace/model_optimizations/results
    volumes:
      - ./results:/workspace/model_optimizations/results

  modelopt_eval:
    build:
      context: ..
      dockerfile: model_optimizations/Dockerfile.modelopt_notebook
    container_name: tx-modelopt-eval
    environment:
      OUTPUT_DIR: /workspace/model_optimizations/results
    volumes:
      - ./results:/workspace/model_optimizations/results
